org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false
kotlin.incremental=false
android.jdkImageTransform.disabled=true
android.experimental.disableJdkImageTransform=true
android.compileOptions.jdkImageTransform.disabled=true
android.overrideVersionCheck=true
android.suppressUnsupportedCompileSdk=35
